### ISSUE TITLE
Shutdown/Reboot Command not Work

### ISSUE THREAD

**Issue by Merschi68** [pauhull/marlinraker#1] opened 2022-10-16 10:17 UTC
Hello, I just installed MarlinrakerOS and updated it. When shutting down, I noticed that the command from the MainSail side doesn't work. The reboot doesn't work either.

**Comment by pauhull** [comment] 2022-10-16 11:41
Hi Merschi68,

thank you for your bug report. I moved it here because the issue is related to Marlinraker, not the actual operating system.

I assume you are talking about these two buttons in the upper right corner of the interface?

![image](https://user-images.githubusercontent.com/22707808/196033126-57a5d80a-a80b-4dcf-86da-011021fd74e3.png)

These buttons do not work because their corresponding API endpoints are not implemented yet. This should be easy to do though. It will be included in the next update.

Best regards

**Comment by Merschi68** [comment] 2022-10-16 14:39
Thanks for the info, I'll wait for the next version then.

**Closed** 2022-10-26 01:18 UTC
